# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres

    ports:
      - "4000:4000"
      - "5432:5432"

  postgres:
    image: postgres:10.16
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USE: postgres
      POSTGRES_DB:
